connection_string = "sqlite:///TMDBclustering.db"
api_url = "https://api.themoviedb.org/3/"
api_key = "e5b4932c233aee0d51fd5895ca16a47b"
language = "en-US"
image_api_url = "https://image.tmdb.org/t/p/"
image_width = "w342"
images_directory = "images"
